format = """
$directory\
$character"""
# move the rest of the prompt to the right
# $git_branch\
# $git_state\
# $git_status\
right_format = """"""
# ❮
# $aws\
#  |
# $gcloud\
#  |
# $kubernetes
# """

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
format = 'via [$symbol($version )($mod_version )]($style)'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[aws]
format = '[$symbol$profile]($style) '
style = "bright-black"
symbol = 'aws::'
force_display = true


[gcloud]
format = '[$symbol$project]($style) '
style = "bright-black"
symbol = 'gcp::'
# [gcloud.project_aliases]


[kubernetes]
format = '[$context::$namespace]($style) '
style = "bright-black"
disabled = false
contexts = []

[cmd_duration]
disabled = true
