color = ''
project-name = 'default'
[default]
account_id = 'acct_1FzSjdIB01GFU0AG'
device_name = 'ENN-LDN-MAC89.local'
display_name = 'Ennismore Dev Account'
live_mode_api_key = 'rk_live_***********************************************************************************************6SgF'
live_mode_key_expires_at = '2023-10-22'
live_mode_pub_key = 'pk_live_zqNly2SHq9pyqMttQ2pCk3Pi00RUFbMrTk'
test_mode_api_key = 'rk_test_51FzSjdIB01GFU0AG20rgcPPA2LmHJeGPqbNLFxxQpCrXrLoQ1rcw6ROxU8pskN6NZ2Ev5PWNh1sW6SzjTInNUEbW00UMrKY8TW'
test_mode_key_expires_at = '2023-10-22'
test_mode_pub_key = 'pk_test_c35UZNsegTOihlL37CMXAMWn00Oz7UhUDK'

