working_directory = "/Volumes/Workspace"

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xff938a"
index = 17

[colors.bright]
black = '0x636e7b'
red = '0xff938a'
green = '0x6bc46d'
yellow = '0xdaaa3f'
blue = '0x6cb6ff'
magenta = '0xb083f0'
cyan = '0x39c5cf'
white = '0x909dab'

[colors.normal]
black = '0x545d68'
red = '0xf47067'
green = '0x57ab5a'
yellow = '0xc69026'
blue = '0x539bf5'
magenta = '0xb083f0'
cyan = '0x39c5cf'
white = '0x909dab'

[colors.primary]
background = "0x22272e"
foreground = "0xadbac7"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "PragmataPro Mono"
style = "Bold"

[font.bold_italic]
family = "PragmataPro Mono"
style = "Bold Italic"

[font.italic]
family = "PragmataPro Mono"
style = "Italic"

[font.normal]
family = "PragmataPro Mono"
style = "Regular"

[font.offset]
x = 0
y = 15

[selection]
save_to_clipboard = true

[window]
#decorations = "buttonless"
#startup_mode = "Windowed"
decorations = "transparent"
startup_mode = "Windowed"
dynamic_padding = true

[window.padding]
x = 10
y = 5
